/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitchenIndexRouteImport } from './routes/kitchen.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerAccountRouteImport } from './routes/customer.account'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer.orders.index'
import { Route as CustomerOrdersOrderIdRouteImport } from './routes/customer.orders.$orderId'

const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchenRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catering': typeof CateringRoute
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/kitchen': typeof KitchenRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catering': typeof CateringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/driver': typeof DriverIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catering': typeof CateringRoute
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/kitchen': typeof KitchenRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/catering'
    | '/customer'
    | '/driver'
    | '/kitchen'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/customer/account'
    | '/customer/checkout'
    | '/admin/'
    | '/customer/'
    | '/driver/'
    | '/kitchen/'
    | '/customer/orders/$orderId'
    | '/customer/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catering'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/customer/account'
    | '/customer/checkout'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/kitchen'
    | '/customer/orders/$orderId'
    | '/customer/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/catering'
    | '/customer'
    | '/driver'
    | '/kitchen'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/customer/account'
    | '/customer/checkout'
    | '/admin/'
    | '/customer/'
    | '/driver/'
    | '/kitchen/'
    | '/customer/orders/$orderId'
    | '/customer/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CateringRoute: typeof CateringRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  KitchenRoute: typeof KitchenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/account': {
      id: '/customer/account'
      path: '/account'
      fullPath: '/customer/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders/$orderId': {
      id: '/customer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/customer/orders/$orderId'
      preLoaderRoute: typeof CustomerOrdersOrderIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerAccountRoute: typeof CustomerAccountRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerOrdersOrderIdRoute: typeof CustomerOrdersOrderIdRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAccountRoute: CustomerAccountRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DriverRouteChildren {
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface KitchenRouteChildren {
  KitchenIndexRoute: typeof KitchenIndexRoute
}

const KitchenRouteChildren: KitchenRouteChildren = {
  KitchenIndexRoute: KitchenIndexRoute,
}

const KitchenRouteWithChildren =
  KitchenRoute._addFileChildren(KitchenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CateringRoute: CateringRoute,
  CustomerRoute: CustomerRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  KitchenRoute: KitchenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
